name: CI/CD Pipeline - Codebeamer Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test & Generate Reports
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile code
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Generate test reports
        if: always()
        run: mvn surefire-report:report-only

      - name: Display test results summary
        if: always()
        run: |
          echo "=== Test Results Summary ==="
          if [ -d "target/surefire-reports" ]; then
            echo "Tests executed. Reports generated in target/surefire-reports/"
            ls -lh target/surefire-reports/
          else
            echo "No test reports found"
          fi

      - name: Upload JUnit XML reports (for Codebeamer)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: target/surefire-reports/TEST-*.xml
          retention-days: 30

      - name: Upload HTML test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-reports
          path: target/site/
          retention-days: 30

      - name: Upload full surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-complete
          path: target/surefire-reports/
          retention-days: 30

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            target/surefire-reports/TEST-*.xml
          check_name: Test Results
          comment_mode: always

      - name: Build JAR artifact
        run: mvn package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
          retention-days: 30

      - name: Upload test results to Codebeamer
        if: always()
        run: |
          chmod +x .github/scripts/upload-to-codebeamer.sh
          .github/scripts/upload-to-codebeamer.sh \
            "${{ secrets.CB_USERNAME }}" \
            "${{ secrets.CB_PASSWORD }}" \
            "${{ secrets.CB_TEST_CASE_TRACKER_ID }}" \
            "${{ secrets.CB_TEST_RUN_TRACKER_ID }}"
        env:
          TEST_CONFIG_ID: ${{ secrets.CB_TEST_CONFIG_ID }}
          RELEASE_ID: ${{ secrets.CB_RELEASE_ID }}
          PACKAGE_PREFIX: ""

      - name: Upload Codebeamer integration artifacts (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codebeamer-integration-debug
          path: |
            target/test_results.zip
            target/upload.log
            target/upload.log.response
          retention-days: 30
